Repository nanoframework/nanoFramework.Azure.Devices, pull requests merged in 2022-01, with the labels that each got.

#49 Adjusting certificate connection when stored on the device and not in code
  Azure.Devices.DeviceClient/DeviceClient.cs
Labels: Type: bug

#60 Fix dps client to use device certificate correctly
  Azure.Devices.DeviceClient/ProvisioningDeviceClient.cs
Labels: Type: bug

#61 Fix Direct Method bug where a formatting error occurs after 10 succes…
  Azure.Devices.DeviceClient/DeviceClient.cs
Labels: Status: under review, Type: bug

#65 optimizing message ack
  nanoFramework.Azure.Devices.Client/DeviceClient.cs
Labels: Type: bug

#74 Make default QoS Level to AtLeastOnce to match default SDK behavior
  README.md
  nanoFramework.Azure.Devices.Client/DeviceClient.cs
Labels: Breaking-Change, Type: Documentation

#88 Adding tests, fixing TwinCollection
  Tests/TwinTests/Properties/AssemblyInfo.cs
  Tests/TwinTests/TwinTest.cs
  Tests/TwinTests/TwinTests.nfproj
  Tests/TwinTests/nano.runsettings
  Tests/TwinTests/packages.config
  nanoFramework.Azure.Devices.Client.sln
  nanoFramework.Azure.Devices.Client/TwinCollection.cs
Labels: Type: Unit Tests, Type: bug
